project:
  type: website
  output-dir: docs

website:
  title: "Reginald Pulley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research 
      - href: CV.qmd
        text: Curriculum Vitae 


format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

